language: ruby
sudo: false
rvm:
  - 2.1.5
env:
  - DATABASE_ENV=test
before_script:
  - bundle exec rake db:create db:migrate
bundler_args: --without development
cache: bundler
addons:
  postgresql: '9.3'
  code_climate:
    repo_token:
