language: ruby
sudo: false
rvm:
  - 2.1.5
env:
  - DATABASE_ENV=test
before_script:
  - bundle exec rake db:create db:migrate
bundler_args: --without development
cache: bundler
addons:
  postgresql: '9.3'
  code_climate:
    repo_token: 6bc1211ff61c0e3f2bd537e783bd38a08803b681ca75945ffd9d9109ca64f374
