development: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  database: youth_match_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: youth_match_test

production:
  url: <%= ENV['DATABASE_URL'].to_s.sub(/^postgres/, 'postgis') %>
