development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: youth_match_development
  host: localhost
  port: 5432

travel_time_development: &default
  database: youthjobs

test:
  <<: *default
  database: youth_match_test
