development: &default
  adapter: postgis
  encoding: unicode
  pool: 5
  database: youth_match_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: youth_match_test

travel_time:
  <<: *default
  database:           ENV['TRAVEL_TIME_DB_NAME']
  host:               ENV['TRAVEL_TIME_DB_HOST']
  password:           ENV['TRAVEL_TIME_DB_PASSWORD']
  schema_search_path: ENV['TRAVEL_TIME_DB_SCHEMA_SEARCH_PATH']
