development: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  database: distance_matrix_development
  host: localhost
  port: 5432

test:
  <<: *default
  database: distance_matrix_test
